---
language: node_js

node_js:
  - node
  - 12
  - 11
  - 10

stages:
  - lint
  - test
  - name: deploy
    if: |
      branch = master AND
      type NOT IN (pull_request) AND
      env(NPM_AUTH_TOKEN) IS present

install:
  - npm ci

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: deploy
      before_script:
        - npm run compile
        - echo "//registry.npmjs.org/:_authToken=\${NPM_AUTH_TOKEN}" > .npmrc
      script:
        - npm publish
      deploy:
        skip_cleanup: true
        provider: npm
        email: eric.s.crosson@utexas.edu
        on:
          tags: true

after_success:
  - npm run coverage
